#
# To deploy:
#
# kubectl apply -f scripts/deployment.yml
#

# Deployment details for loading library-service image (book_catalog)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-service
  labels:
    app: library-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-service
  template:
    metadata:
      labels:
        app: library-service
    spec:
      containers:
      - name: library-service
        image: harshith.azurecr.io/library-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "4000"
        - name: DATABASE_URL
          value: "postgresql://week09_m9m4_user:QNAS4IhQVijSlkGr5d3FkR62P9HYSkUx@dpg-crh5jhl6l47c73c2u1ag-a.oregon-postgres.render.com/week09_m9m4"
---
apiVersion: v1
kind: Service
metadata:
  name: library-service
spec:
  selector:
    app: library-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 31000
      targetPort: 4000

---

# Deployment details for loading inventory-service image (inventory_management)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  labels:
    app: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: harshith.azurecr.io/inventory-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "5000"
        - name: DATABASE_URL
          value: "postgresql://week09_m9m4_user:QNAS4IhQVijSlkGr5d3FkR62P9HYSkUx@dpg-crh5jhl6l47c73c2u1ag-a.oregon-postgres.render.com/week09_m9m4"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: inventory-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 32000
      targetPort: 5000

